### ISSUE TITLE
no phone

### ISSUE THREAD

**Issue by EliBP** [jacobragsdale/debate-deck#4]
hey, my phone completely stopped working - it won't even turn on. so.. yeah here I am opening a GitHub issue

**Comment by jacobragsdale** [comment]
discord
swagsdale#5149

**Comment by EliBP** [comment]
blocked on my school computer. they have these things LOCKED down.

**Comment by jacobragsdale** [comment]
rip.. I have an old iPhone you could borrow. If you find a chat app you can access let me know

**Comment by EliBP** [comment]
Ok.. so outlook email with personal accounts isn't blocked lmao. im elibp13@outlook.com
